#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2019-01-30 09:44:36
# @Author  : Onedi (Onedi@qq.com)
# @Link    : ${link}
# @Version : $Id$

import requests 
import json
import random
from requests.packages import urllib3

url = 'https://eddid-api.ntdev.be/eddid-api-develop/apply/create'
headers = {
    'Content-Type' : 'application/json' ,
    'X-Token' : 'eyJraWQiOiJSejNcLzBrMzY0alZZK2NVVUQ4bWpjdEhYdHgrWTNROENNXC9FcG52OGhXbkE9IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiI3YWYzYWRhOS0yZmY5LTQ1MWQtODdkNy0xNjI5ZWVjZWQyNDMiLCJjb2duaXRvOmdyb3VwcyI6WyJhZG1pbiJdLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiY29nbml0bzpwcmVmZXJyZWRfcm9sZSI6ImFybjphd3M6aWFtOjo4MzI0MzE4NjQ2NjY6cm9sZVwvZGV2LWVkZGlkLWNvZ25pdG8tYWRtaW4tcm9sZSIsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC5hcC1zb3V0aGVhc3QtMS5hbWF6b25hd3MuY29tXC9hcC1zb3V0aGVhc3QtMV91OWZ6N2x5b04iLCJjb2duaXRvOnVzZXJuYW1lIjoiYWRtaW4iLCJnaXZlbl9uYW1lIjoidGVzdCIsImNvZ25pdG86cm9sZXMiOlsiYXJuOmF3czppYW06OjgzMjQzMTg2NDY2Njpyb2xlXC9kZXYtZWRkaWQtY29nbml0by1hZG1pbi1yb2xlIl0sImF1ZCI6IjUxM2pmY2t0cjFtNmV2b2dmcXU3b3NrN3BhIiwiZXZlbnRfaWQiOiIyMTRiMTc5YS01YjNlLTExZTktOWJhMy0yM2I5M2ZhNmZkY2QiLCJ0b2tlbl91c2UiOiJpZCIsImF1dGhfdGltZSI6MTU1NDg2NTgwMSwiZXhwIjoxNTU0ODY5NDAxLCJpYXQiOjE1NTQ4NjU4MDEsImZhbWlseV9uYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluMTIzNEAxNjMuY29tIn0.dXSz_gravDqvhd5guq2e_F1ziyj_5dC3-cGoPgPn6sugBj7JGSWpfPtaIKIDzeXAgTPhRTHGRa_c8mBeigUu7pefHicxj0Cim953qeUBy-XVeMsYHzpd3-UvCZ0IGGq-43xouYi5jBwwb6dH1h7USR2RvzjSQDMTuXggP9ODNVfXdgd9Yo1bf0TG0CY3q3uBRgdf11eVfn7J-bRv5OLwvti9ncC790uqiGajvhOPWfu0ugEHsb8T11axqRcd-ILKt5tHHodgEPAEGSr-7FEdIGaH9khMyrZ5wBixQpVP5RCIdu87qeGYOhKlhIXnqcKtk2ue7v6TsR7ZB6kTODiovw'
}


data = {
    "applicationFor": "individual",
    # "applicationFor": "joint",    
    # goldSpot 黄金
    "accountType": ["securitiesCash", "leveragedForeignExchangeAccountMargin","futuresMargin","securitiesDayTradeMargin", "bullionMargin"],
    # "accountType": ["bullionMargin"],
    #mobile:手机;visitingAccount:亲临开户;postal:邮递;onlineApplication:网上开户申请
    "accountOpeningWay": "visitingAccount",  #开户方式,
    "personalInfoDeclartion": "Y",
    # "customerSource": "ballFives",    
    # "customerSource": "app",    
    "customerSource": "crm",    
    "mailLanguage": "en",
    "appBankName": "",
    "appBankAccount": "",
    "appCertSn": "",
    "currency": "HKD",
    "bankAccount": [],
    "isMarginAccount": "",
    "marginAccountName": "",
    "marginAccountNumber": "",
    "isDiscretion": "",
    "discretionName": "",
    "discretionNumber": "",
    "isCompanyAccounts": "",
    "companyAccountsName": "",
    "companyAccountsNumber": "",
    "learnHow": ["advertising"],
    "learnHowOther": "",
    "learnHowCode": "EDYL",
    "IBparentId": "",
    "isBeneficiary": "Y",
    "beneficiaryName": "",
    "isOrders": "Y",
    "tradingAuthorization": [],
    "ordersName": "",
    "isRelatedAccounts": ["HK"],
    "relatedAccountsOpt": [{
        "id": 5888414,
        "residenceJurisdiction": "",
        "taxId": ""
    }],
    "receipt": ["download"],
    "agreeToTheTerms": "Y",
    "jointReportingStandardStatement": "Y",
    "privacyPolicyStatement": "Y",
    "customerStatement": "Y",
    "riskDisclosureStatement": "Y",
    "termsAndConditionsOfBusiness": "Y",
    "client": [{
        "riskInfo": {
            "passportMaterial": ["publicDropbox/BcPJde9SCkFdFssQaJz9KYRNMbfyYm2t.jpeg"],
            "addressVerificationMaterials": ["publicDropbox/8pRBJ8ssFtibKGdF4kw1r6irkijMe9G2.jpeg"],
            "bankCardMaterials": ["publicDropbox/NRccBw9hbN2ZXXbfajmrZw4TR17HNS3F.jpeg"],
            "referralCode": "",
            "isErr": False,
            "errText": "",
            "otherInformation": [],
            "proofOfIncome": [],
            "totalAnnualCustomerRevenueHK": "lt200000",
            "customerNetAssetValueHK": "lt1000000",
            "sourceOfWealth": ["savings"],
            "sourceOfWealthOther": "",
            "securities": "lt1Year",
            "CBBC": "lt1Year",
            "warrants": "lt1Year",
            "futures": "lt1Year",
            "options": "lt1Year",
            "otherInvestment": "",
            "otherInvestmentText": "",
            "foreignExchange": "lt1Year",
            "isLearnAboutProducts": "Y",
            "isIndustryExperience": "Y",
            "isStocks": "Y",
            "isTradingStructureAggree": "N",
            "isApplyToOpenTradingStructure": "Y",
            "isBankruptcy": "N",
            "bankruptcyDate": "",
            "bankruptcyProve": [],
            "isInAgtJobs": "N",
            "agtPosition": "",
            "isBondFuturesClientsConnected": "N",
            "agtName": "",
            "isAcquaintHighLevel": "N",
            "acquaintHighLevelInstructions": "",
            "acquaintHighLevelInstructionsProve": [],
            "isAmericanResidents": "N",
            "americanResidentsTaxId": "",
            "isAmericanResidentsb": "N",
            "americanResidentsTaxIdb": "",
            "isPoliticalFigure": "N",
            "politicalFigureName": "",
            "purposeOfInvestment": "hedging",
            "riskTolerance": "low"
        },
        "title": "mrs",
        "parentId": "sales_t1" ,
        "lastName": "last",
        "firstName": "first",
        "chineseName": "Test",
        "pastEnglishName": "",
        "pastChineseName": "",
        "idType": "2",
        "idNumber": "%s423523%s" %(random.randint(0,1001),random.randint(0,10600)),
        "countryIssue": "CHN",
        "nationality": "CHN",
        "birthPlace": "CHN",
        "birthday": 894384000000,
        "email": "%sonedi2s%s@qq.com" %(random.randint(0,1000),random.randint(0,10300)),
        # "email": "onedi.zheng@newtype.io" ,
        "phoneAreaCode": "HKG",
        "phone": "%s6253%s" %(random.randint(0,100002),random.randint(0,10502)),
        # "phone": "15089514626" ,
        "address": "3466324364",
        "addressMail": "34632646345",
        # "mailLanguage": "zh-hans",
        "mailLanguage": "zh-hans",
        "employment": "retired",
        "employmentOther": "",
        "occupation": "",
        "employedPeriod": "",
        "employer": "",
        "businessType": "",
        "businessAddress": "",
        "businessPhone": ""
    },
    # {
    #     "riskInfo": {
    #         "passportMaterial": ["publicDropbox/BcPJde9SCkFdFssQaJz9KYRNMbfyYm2t.jpeg"],
    #         "addressVerificationMaterials": ["publicDropbox/8pRBJ8ssFtibKGdF4kw1r6irkijMe9G2.jpeg"],
    #         "bankCardMaterials": ["publicDropbox/NRccBw9hbN2ZXXbfajmrZw4TR17HNS3F.jpeg"],
    #         "referralCode": "",
    #         "isErr": False,
    #         "errText": "",
    #         "otherInformation": [],
    #         "proofOfIncome": [],
    #         "totalAnnualCustomerRevenueHK": "lt200000",
    #         "customerNetAssetValueHK": "lt1000000",
    #         "sourceOfWealth": ["savings"],
    #         "sourceOfWealthOther": "",
    #         "securities": "lt1Year",
    #         "CBBC": "lt1Year",
    #         "warrants": "lt1Year",
    #         "futures": "lt1Year",
    #         "options": "lt1Year",
    #         "otherInvestment": "",
    #         "otherInvestmentText": "",
    #         "foreignExchange": "lt1Year",
    #         "isLearnAboutProducts": "Y",
    #         "isIndustryExperience": "Y",
    #         "isStocks": "Y",
    #         "isTradingStructureAggree": "N",
    #         "isApplyToOpenTradingStructure": "Y",
    #         "isBankruptcy": "N",
    #         "bankruptcyDate": "",
    #         "bankruptcyProve": [],
    #         "isInAgtJobs": "N",
    #         "agtPosition": "",
    #         "isBondFuturesClientsConnected": "N",
    #         "agtName": "",
    #         "isAcquaintHighLevel": "N",
    #         "acquaintHighLevelInstructions": "",
    #         "acquaintHighLevelInstructionsProve": [],
    #         "isAmericanResidents": "N",
    #         "americanResidentsTaxId": "",
    #         "isAmericanResidentsb": "N",
    #         "americanResidentsTaxIdb": "",
    #         "isPoliticalFigure": "N",
    #         "politicalFigureName": "",
    #         "purposeOfInvestment": "hedging",
    #         "riskTolerance": "low"
    #     },
        # "title": "mrs",
        # "parentId": "kwokwah.wong" ,
        # "lastName": "32455432",
        # "firstName": "3245532523",
        # "chineseName": "5235234",
        # "pastEnglishName": "",
        # "pastChineseName": "",
        # "idType": "2",
        # "idNumber": "%s423523%s" %(random.randint(0,100001),random.randint(0,106000)),
        # "countryIssue": "CHN",
        # "nationality": "CHN",
        # "birthPlace": "CHN",
        # "birthday": 894384000000,
        # "email": "%sonedi2s%s@qq.com" %(random.randint(0,1000),random.randint(0,10300)),
        # # "email": "onedi@qq.com" ,
        # "phoneAreaCode": "HKG",
        # "phone": "%s6253%s" %(random.randint(0,100002),random.randint(0,100502)),
        # # "phone": "15089514626" ,
        # "address": "3466324364",
        # "addressMail": "34632646345",
        # # "mailLanguage": "zh-hans",
        # "mailLanguage": "zh-hans",
        # "employment": "retired",
        # "employmentOther": "",
        # "occupation": "",
        # "employedPeriod": "",
        # "employer": "",
        # "businessType": "",
        # "businessAddress": "",
        # "businessPhone": ""
    # }
    ]
}

# print(data)
urllib3.disable_warnings()
resp = requests.post(url, headers=headers, data=json.dumps(data), verify=False)
print(resp.json())

